/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Csrf
         * @description Ensures the CSRF cookie is set (the SPA calls this on startup).
         */
        get: operations["apps_core_api_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["apps_core_api_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["apps_core_api_system_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/processing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Processing Settings */
        put: operations["apps_core_api_update_processing_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/enhancement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Enhancement Settings */
        put: operations["apps_core_api_update_enhancement_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processing/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Processing Queue */
        get: operations["apps_core_api_processing_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Log */
        get: operations["apps_core_api_audit_log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session State */
        get: operations["apps_accounts_api_session_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Password */
        post: operations["apps_accounts_api_login_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Totp */
        post: operations["apps_accounts_api_login_totp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Recovery */
        post: operations["apps_accounts_api_login_recovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/webauthn/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Webauthn Options */
        post: operations["apps_accounts_api_login_webauthn_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/webauthn/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Webauthn Verify */
        post: operations["apps_accounts_api_login_webauthn_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout View */
        post: operations["apps_accounts_api_logout_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthenticate */
        post: operations["apps_accounts_api_reauthenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Totp Setup */
        post: operations["apps_accounts_api_totp_setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/totp/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Totp Confirm */
        post: operations["apps_accounts_api_totp_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/webauthn/register/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webauthn Register Options */
        post: operations["apps_accounts_api_webauthn_register_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/webauthn/register/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webauthn Register Verify */
        post: operations["apps_accounts_api_webauthn_register_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/recovery-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Recovery Codes */
        post: operations["apps_accounts_api_regenerate_recovery_codes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["apps_accounts_api_list_devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/devices/{kind}/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Device */
        delete: operations["apps_accounts_api_delete_device"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["apps_accounts_api_change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["apps_accounts_api_list_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/sessions/revoke-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Other Sessions */
        post: operations["apps_accounts_api_revoke_other_sessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Session */
        delete: operations["apps_accounts_api_revoke_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sign In Activity
         * @description Sign-ins (successful and failed) of the current user and what happened in each session.
         */
        get: operations["apps_accounts_api_sign_in_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["apps_documents_api_list_documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Web Upload
         * @description Upload a PDF from the web UI. Uses the same durable intake and pipeline as scanners.
         */
        post: operations["apps_documents_api_web_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Update */
        post: operations["apps_documents_api_bulk_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Detail */
        get: operations["apps_documents_api_document_detail"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["apps_documents_api_delete_document"];
        options?: never;
        head?: never;
        /** Update Document */
        patch: operations["apps_documents_api_update_document"];
        trace?: never;
    };
    "/api/v1/documents/{doc_id}/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Unread */
        post: operations["apps_documents_api_mark_unread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{doc_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document File */
        get: operations["apps_documents_api_document_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{doc_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Thumbnail */
        get: operations["apps_documents_api_document_thumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{doc_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Text */
        get: operations["apps_documents_api_document_text"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{doc_id}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Structure */
        get: operations["apps_documents_api_document_structure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{doc_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess */
        post: operations["apps_documents_api_reprocess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Folders */
        get: operations["apps_taxonomy_api_list_folders"];
        put?: never;
        /** Create Folder */
        post: operations["apps_taxonomy_api_create_folder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Folder */
        delete: operations["apps_taxonomy_api_delete_folder"];
        options?: never;
        head?: never;
        /** Update Folder */
        patch: operations["apps_taxonomy_api_update_folder"];
        trace?: never;
    };
    "/api/v1/document-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Types */
        get: operations["apps_taxonomy_api_list_types"];
        put?: never;
        /** Create Type */
        post: operations["apps_taxonomy_api_create_type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/document-types/{type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Type */
        delete: operations["apps_taxonomy_api_delete_type"];
        options?: never;
        head?: never;
        /** Update Type */
        patch: operations["apps_taxonomy_api_update_type"];
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["apps_taxonomy_api_list_tags"];
        put?: never;
        /** Create Tag */
        post: operations["apps_taxonomy_api_create_tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["apps_taxonomy_api_delete_tag"];
        options?: never;
        head?: never;
        /** Update Tag */
        patch: operations["apps_taxonomy_api_update_tag"];
        trace?: never;
    };
    "/api/v1/tags/{tag_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Tag */
        post: operations["apps_taxonomy_api_merge_tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correspondents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Correspondents */
        get: operations["apps_taxonomy_api_list_correspondents"];
        put?: never;
        /** Create Correspondent */
        post: operations["apps_taxonomy_api_create_correspondent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correspondents/{corr_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Correspondent */
        delete: operations["apps_taxonomy_api_delete_correspondent"];
        options?: never;
        head?: never;
        /** Update Correspondent */
        patch: operations["apps_taxonomy_api_update_correspondent"];
        trace?: never;
    };
    "/api/v1/correspondents/{corr_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Correspondent */
        post: operations["apps_taxonomy_api_merge_correspondent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Series */
        get: operations["apps_taxonomy_api_list_series"];
        put?: never;
        /** Create Series */
        post: operations["apps_taxonomy_api_create_series"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series Detail */
        get: operations["apps_taxonomy_api_series_detail"];
        put?: never;
        post?: never;
        /** Delete Series */
        delete: operations["apps_taxonomy_api_delete_series"];
        options?: never;
        head?: never;
        /** Update Series */
        patch: operations["apps_taxonomy_api_update_series"];
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["apps_taxonomy_api_list_rules"];
        put?: never;
        /** Create Rule */
        post: operations["apps_taxonomy_api_create_rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["apps_taxonomy_api_delete_rule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scanners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scanners */
        get: operations["apps_scanners_api_list_scanners"];
        put?: never;
        /** Create Scanner */
        post: operations["apps_scanners_api_create_scanner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scanners/{scanner_id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Token */
        post: operations["apps_scanners_api_rotate_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scanners/{scanner_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Scanner */
        post: operations["apps_scanners_api_revoke_scanner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scanners/{scanner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Scanner */
        delete: operations["apps_scanners_api_delete_scanner"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** OverviewOut */
        OverviewOut: {
            /** Total */
            total: number;
            /** New */
            new: number;
            /** Unread */
            unread: number;
            /** Todo */
            todo: number;
            /** Important */
            important: number;
            /** Failed */
            failed: number;
            /** Processing */
            processing: number;
            /** Waiting For Storage */
            waiting_for_storage: number;
            /** Series Suggestions */
            series_suggestions: number;
            /** Suggested Tags */
            suggested_tags: number;
        };
        /** EnhanceSettingsOut */
        EnhanceSettingsOut: {
            /** Enabled */
            enabled: boolean;
            /** Rotate */
            rotate: boolean;
            /** Rotate Min Confidence */
            rotate_min_confidence: number;
            /** Deskew */
            deskew: boolean;
            /** Deskew Min Angle */
            deskew_min_angle: number;
            /** Deskew Max Angle */
            deskew_max_angle: number;
            /** Crop */
            crop: boolean;
            /** Crop Max Fraction */
            crop_max_fraction: number;
            /** Cleanup */
            cleanup: boolean;
            /** Cleanup Background */
            cleanup_background: boolean;
            /** Cleanup Contrast */
            cleanup_contrast: boolean;
            /** Cleanup Despeckle */
            cleanup_despeckle: boolean;
            /**
             * Cleanup Strength
             * @enum {string}
             */
            cleanup_strength: "low" | "medium" | "high";
            /** Remove Blank */
            remove_blank: boolean;
            /** Blank Threshold */
            blank_threshold: number;
        };
        /** StorageStatus */
        StorageStatus: {
            /** Backend */
            backend: string;
            /** Ok */
            ok: boolean | null;
            /** Needs Reauth */
            needs_reauth: boolean;
            /** Message */
            message: string;
            /** Checked At */
            checked_at: string | null;
        };
        /** SystemStatus */
        SystemStatus: {
            /** Version */
            version: string;
            /**
             * Default Ocr Backend
             * @enum {string}
             */
            default_ocr_backend: "ocrmypdf" | "docling";
            /**
             * Docling Field Detection
             * @enum {string}
             */
            docling_field_detection: "layout" | "vlm" | "hybrid";
            storage: components["schemas"]["StorageStatus"];
            /** Worker Online */
            worker_online: boolean;
            /** Worker Last Seen */
            worker_last_seen: string | null;
            /** Processing Concurrency */
            processing_concurrency: number;
            scan_enhancement: components["schemas"]["EnhanceSettingsOut"];
            /** Queued Jobs */
            queued_jobs: number;
            /** Running Jobs */
            running_jobs: number;
            /** Failed Jobs */
            failed_jobs: number;
        };
        /** ProcessingSettingsOut */
        ProcessingSettingsOut: {
            /**
             * Default Ocr Backend
             * @enum {string}
             */
            default_ocr_backend: "ocrmypdf" | "docling";
            /**
             * Docling Field Detection
             * @enum {string}
             */
            docling_field_detection: "layout" | "vlm" | "hybrid";
            /** Processing Concurrency */
            processing_concurrency: number;
        };
        /** ProcessingSettingsIn */
        ProcessingSettingsIn: {
            /** Default Ocr Backend */
            default_ocr_backend?: ("ocrmypdf" | "docling") | null;
            /** Docling Field Detection */
            docling_field_detection?: ("layout" | "vlm" | "hybrid") | null;
            /** Processing Concurrency */
            processing_concurrency?: number | null;
        };
        /**
         * EnhanceSettingsIn
         * @description Partial update: omitted fields keep their current value.
         */
        EnhanceSettingsIn: {
            /** Enabled */
            enabled?: boolean | null;
            /** Rotate */
            rotate?: boolean | null;
            /** Rotate Min Confidence */
            rotate_min_confidence?: number | null;
            /** Deskew */
            deskew?: boolean | null;
            /** Deskew Min Angle */
            deskew_min_angle?: number | null;
            /** Deskew Max Angle */
            deskew_max_angle?: number | null;
            /** Crop */
            crop?: boolean | null;
            /** Crop Max Fraction */
            crop_max_fraction?: number | null;
            /** Cleanup */
            cleanup?: boolean | null;
            /** Cleanup Background */
            cleanup_background?: boolean | null;
            /** Cleanup Contrast */
            cleanup_contrast?: boolean | null;
            /** Cleanup Despeckle */
            cleanup_despeckle?: boolean | null;
            /** Cleanup Strength */
            cleanup_strength?: ("low" | "medium" | "high") | null;
            /** Remove Blank */
            remove_blank?: boolean | null;
            /** Blank Threshold */
            blank_threshold?: number | null;
        };
        /** ProcessingQueueItem */
        ProcessingQueueItem: {
            /** Id */
            id: number;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Title */
            title: string;
            /** State */
            state: string;
            /** Stage */
            stage: string;
            /** Backend */
            backend: string;
            /** Attempts */
            attempts: number;
            /** Error */
            error: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
        };
        /** ProcessingQueueOut */
        ProcessingQueueOut: {
            /** Concurrency */
            concurrency: number;
            /** Queued */
            queued: components["schemas"]["ProcessingQueueItem"][];
            /** Running */
            running: components["schemas"]["ProcessingQueueItem"][];
            /** History */
            history: components["schemas"]["ProcessingQueueItem"][];
        };
        /** AuditOut */
        AuditOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Actor Type */
            actor_type: string;
            /** Actor Label */
            actor_label: string;
            /** Action */
            action: string;
            /** Target */
            target: string;
            /** Ip */
            ip: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** MfaMethodsOut */
        MfaMethodsOut: {
            /** Webauthn */
            webauthn: boolean;
            /** Totp */
            totp: boolean;
            /** Recovery */
            recovery: boolean;
        };
        /** PreviousLoginOut */
        PreviousLoginOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Ip */
            ip: string | null;
            /** User Agent */
            user_agent: string;
            /** Method */
            method: string;
        };
        /** SessionStateOut */
        SessionStateOut: {
            /** Authenticated */
            authenticated: boolean;
            /** Mfa Complete */
            mfa_complete: boolean;
            /** Needs Enrollment */
            needs_enrollment: boolean;
            pending_mfa?: components["schemas"]["MfaMethodsOut"] | null;
            /** Username */
            username?: string | null;
            /**
             * Has Recovery Codes
             * @default false
             */
            has_recovery_codes: boolean;
            previous_login?: components["schemas"]["PreviousLoginOut"] | null;
            /**
             * Failed Since Previous Login
             * @default 0
             */
            failed_since_previous_login: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** CodeIn */
        CodeIn: {
            /** Code */
            code: string;
        };
        /** CredentialIn */
        CredentialIn: {
            /** Credential */
            credential: {
                [key: string]: unknown;
            };
            /**
             * Name
             * @default
             */
            name: string;
        };
        /** PasswordIn */
        PasswordIn: {
            /** Password */
            password: string;
        };
        /** TotpSetupOut */
        TotpSetupOut: {
            /** Secret */
            secret: string;
            /** Uri */
            uri: string;
        };
        /** RecoveryCodesOut */
        RecoveryCodesOut: {
            /** Codes */
            codes: string[];
        };
        /** DeviceOut */
        DeviceOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at?: string | null;
        };
        /** ChangePasswordIn */
        ChangePasswordIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /** Current */
            current: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Ip */
            ip: string | null;
            /** User Agent */
            user_agent: string;
        };
        /** RevokedOut */
        RevokedOut: {
            /** Revoked */
            revoked: number;
        };
        /** ActivityActionOut */
        ActivityActionOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Action */
            action: string;
            /** Target */
            target: string;
            /** Target Title */
            target_title?: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** SignInOut */
        SignInOut: {
            /** Id */
            id: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Outcome */
            outcome: string;
            /** Method */
            method: string;
            /** Ip */
            ip: string | null;
            /** User Agent */
            user_agent: string;
            /** Current */
            current: boolean;
            /** Active */
            active: boolean;
            /** Last Activity At */
            last_activity_at: string | null;
            /** Actions */
            actions: components["schemas"]["ActivityActionOut"][];
        };
        /** DocumentFilters */
        DocumentFilters: {
            /**
             * Q
             * @default
             */
            q: string;
            /** Folder */
            folder?: number[];
            /**
             * Subfolders
             * @default false
             */
            subfolders: boolean;
            /**
             * Unfiled
             * @default false
             */
            unfiled: boolean;
            /** Document Type */
            document_type?: number[];
            /** Correspondent */
            correspondent?: number[];
            /** Tag */
            tag?: number[];
            /** Series */
            series?: number | null;
            /** Status */
            status?: ("new" | "todo" | "done")[];
            /** Important */
            important?: boolean | null;
            /** Unread */
            unread?: boolean | null;
            /** Processing */
            processing?: ("pending" | "running" | "done" | "failed")[];
            /** Uploaded From */
            uploaded_from?: string | null;
            /** Uploaded To */
            uploaded_to?: string | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /**
             * Sort
             * @default relevance
             * @enum {string}
             */
            sort: "relevance" | "uploaded" | "-uploaded" | "date" | "-date";
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 25
             */
            page_size: number;
        };
        /** DocumentListItem */
        DocumentListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            folder: components["schemas"]["FolderRefOut"] | null;
            document_type: components["schemas"]["RefOut"] | null;
            correspondent: components["schemas"]["RefOut"] | null;
            series: components["schemas"]["RefOut"] | null;
            /** Period Label */
            period_label: string;
            /** Tags */
            tags: components["schemas"]["TagRefOut"][];
            /** Status */
            status: string;
            /** Is Important */
            is_important: boolean;
            /** Is Read */
            is_read: boolean;
            /** Document Date */
            document_date: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Page Count */
            page_count: number;
            /** Processing State */
            processing_state: string;
            /** Processing Error */
            processing_error: string;
            /** Has Series Suggestion */
            has_series_suggestion: boolean;
            /** Score */
            score?: number | null;
            snippet?: components["schemas"]["SnippetOut"] | null;
        };
        /** DocumentPage */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["DocumentListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** FolderRefOut */
        FolderRefOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** RefOut */
        RefOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** SnippetOut */
        SnippetOut: {
            /** Text */
            text: string;
            /** Highlights */
            highlights: number[][];
        };
        /** TagRefOut */
        TagRefOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Source */
            source: string;
        };
        /** WebUploadOut */
        WebUploadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Duplicate */
            duplicate: boolean;
        };
        /** BulkOut */
        BulkOut: {
            /** Updated */
            updated: number;
        };
        /** BulkAction */
        BulkAction: {
            /** Ids */
            ids: string[];
            /**
             * Action
             * @enum {string}
             */
            action: "mark_read" | "mark_unread" | "status_done" | "status_todo" | "status_new" | "important" | "unimportant" | "move" | "reprocess";
            /** Folder Id */
            folder_id?: number | null;
            reprocess?: components["schemas"]["ReprocessIn"] | null;
        };
        /** ReprocessIn */
        ReprocessIn: {
            /**
             * Stage
             * @default ocr
             * @enum {string}
             */
            stage: "ocr" | "analyze";
            /** Backend */
            backend?: ("ocrmypdf" | "docling") | null;
            enhancement?: components["schemas"]["EnhanceSettingsIn"] | null;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            folder: components["schemas"]["FolderRefOut"] | null;
            document_type: components["schemas"]["RefOut"] | null;
            correspondent: components["schemas"]["RefOut"] | null;
            series: components["schemas"]["RefOut"] | null;
            /** Period Label */
            period_label: string;
            /** Tags */
            tags: components["schemas"]["TagRefOut"][];
            /** Status */
            status: string;
            /** Is Important */
            is_important: boolean;
            /** Is Read */
            is_read: boolean;
            /** Document Date */
            document_date: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Page Count */
            page_count: number;
            /** Processing State */
            processing_state: string;
            /** Processing Error */
            processing_error: string;
            /** Has Series Suggestion */
            has_series_suggestion: boolean;
            /** Score */
            score?: number | null;
            snippet?: components["schemas"]["SnippetOut"] | null;
            series_suggestion: components["schemas"]["RefOut"] | null;
            /** Field Sources */
            field_sources: {
                [key: string]: unknown;
            };
            /** Extracted */
            extracted: {
                [key: string]: unknown;
            };
            /** Scanner Metadata */
            scanner_metadata: {
                [key: string]: unknown;
            };
            /** Original Filename */
            original_filename: string;
            /** Received From */
            received_from: string | null;
            /** Size */
            size: number;
            /** Processing Stage */
            processing_stage: string;
            /** Ocr Backend */
            ocr_backend: string;
            /** Stored */
            stored: boolean;
            /** Original Page Count */
            original_page_count: number;
            /** Enhanced */
            enhanced: boolean;
            /** Enhancement */
            enhancement: {
                [key: string]: unknown;
            };
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** EventOut */
        EventOut: {
            /** Stage */
            stage: string;
            /** Outcome */
            outcome: string;
            /** Message */
            message: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentPatch */
        DocumentPatch: {
            /** Title */
            title?: string | null;
            /** Document Date */
            document_date?: string | null;
            /**
             * Clear Document Date
             * @default false
             */
            clear_document_date: boolean;
            /** Document Type Id */
            document_type_id?: number | null;
            /** Folder Id */
            folder_id?: number | null;
            /**
             * Clear Folder
             * @default false
             */
            clear_folder: boolean;
            /** Correspondent Id */
            correspondent_id?: number | null;
            /** Correspondent Name */
            correspondent_name?: string | null;
            /**
             * Clear Correspondent
             * @default false
             */
            clear_correspondent: boolean;
            /** Tag Ids */
            tag_ids?: number[] | null;
            /** Tag Names */
            tag_names?: string[] | null;
            /** Status */
            status?: ("new" | "todo" | "done") | null;
            /** Is Important */
            is_important?: boolean | null;
            /** Series Id */
            series_id?: number | null;
            /**
             * Clear Series
             * @default false
             */
            clear_series: boolean;
            /**
             * Accept Series Suggestion
             * @default false
             */
            accept_series_suggestion: boolean;
            /**
             * Reject Series Suggestion
             * @default false
             */
            reject_series_suggestion: boolean;
        };
        /** TextOut */
        TextOut: {
            /** Text */
            text: string;
            /** Format */
            format: string;
            /** Backend */
            backend: string;
        };
        /** StructureOut */
        StructureOut: {
            /** Backend */
            backend: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** FolderOut */
        FolderOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
            /** Path */
            path: string;
            /** Color */
            color: string;
            /** Document Count */
            document_count: number;
        };
        /** FolderIn */
        FolderIn: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
            /** Color */
            color?: string | null;
        };
        /** FolderPatch */
        FolderPatch: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Move To Root
             * @default false
             */
            move_to_root: boolean;
        };
        /** TypeOut */
        TypeOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Document Count */
            document_count: number;
        };
        /** NamedIn */
        NamedIn: {
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
        };
        /** TagOut */
        TagOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Is Suggested */
            is_suggested: boolean;
            /** Aliases */
            aliases: string[];
            /** Document Count */
            document_count: number;
        };
        /** TagPatch */
        TagPatch: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
            /** Aliases */
            aliases?: string[] | null;
        };
        /** MergeIn */
        MergeIn: {
            /** Target Id */
            target_id: number;
        };
        /** CorrespondentOut */
        CorrespondentOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
            /** Document Count */
            document_count: number;
        };
        /** CorrespondentPatch */
        CorrespondentPatch: {
            /** Name */
            name?: string | null;
            /** Aliases */
            aliases?: string[] | null;
        };
        /** SeriesOut */
        SeriesOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Cadence */
            cadence: string;
            /** Is Suggested */
            is_suggested: boolean;
            /** Correspondent */
            correspondent: string | null;
            /** Document Type */
            document_type: string | null;
            /** Document Count */
            document_count: number;
            /** Latest Date */
            latest_date: string | null;
        };
        /** SeriesIn */
        SeriesIn: {
            /** Name */
            name: string;
            /** Correspondent Id */
            correspondent_id?: number | null;
            /** Document Type Id */
            document_type_id?: number | null;
        };
        /** SeriesDetail */
        SeriesDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Cadence */
            cadence: string;
            /** Is Suggested */
            is_suggested: boolean;
            /** Correspondent */
            correspondent: string | null;
            /** Document Type */
            document_type: string | null;
            /** Document Count */
            document_count: number;
            /** Latest Date */
            latest_date: string | null;
            /** Members */
            members: components["schemas"]["SeriesMemberOut"][];
            /** Missing Periods */
            missing_periods: string[];
        };
        /** SeriesMemberOut */
        SeriesMemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Period Label */
            period_label: string;
            /** Document Date */
            document_date: string | null;
            /** Status */
            status: string;
        };
        /** SeriesPatch */
        SeriesPatch: {
            /** Name */
            name?: string | null;
            /** Cadence */
            cadence?: string | null;
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
        };
        /** RuleOut */
        RuleOut: {
            /** Id */
            id: number;
            /** Phrase */
            phrase: string;
            /** Correspondent */
            correspondent: string | null;
            /** Document Type */
            document_type: string | null;
            /** Tags */
            tags: string[];
        };
        /** RuleIn */
        RuleIn: {
            /** Phrase */
            phrase: string;
            /** Correspondent Id */
            correspondent_id?: number | null;
            /** Document Type Id */
            document_type_id?: number | null;
            /**
             * Tag Ids
             * @default []
             */
            tag_ids: number[];
        };
        /** ScannerOut */
        ScannerOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Token Prefix */
            token_prefix: string;
            /** Scopes */
            scopes: string[];
            /** Allowed Ips */
            allowed_ips: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Last Used Ip */
            last_used_ip: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Active */
            active: boolean;
            /** Document Count */
            document_count: number;
        };
        /** ScannerCreated */
        ScannerCreated: {
            scanner: components["schemas"]["ScannerOut"];
            /** Token */
            token: string;
        };
        /** ScannerIn */
        ScannerIn: {
            /** Name */
            name: string;
            /**
             * Allow Status
             * @default true
             */
            allow_status: boolean;
            /**
             * Allowed Ips
             * @default []
             */
            allowed_ips: string[];
            /** Expires At */
            expires_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apps_core_api_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_core_api_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
        };
    };
    apps_core_api_system_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    apps_core_api_update_processing_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessingSettingsIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingSettingsOut"];
                };
            };
        };
    };
    apps_core_api_update_enhancement_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnhanceSettingsIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhanceSettingsOut"];
                };
            };
        };
    };
    apps_core_api_processing_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingQueueOut"];
                };
            };
        };
    };
    apps_core_api_audit_log: {
        parameters: {
            query?: {
                limit?: number;
                before?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"][];
                };
            };
        };
    };
    apps_accounts_api_session_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
        };
    };
    apps_accounts_api_login_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
        };
    };
    apps_accounts_api_login_totp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
        };
    };
    apps_accounts_api_login_recovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
        };
    };
    apps_accounts_api_login_webauthn_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_login_webauthn_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
        };
    };
    apps_accounts_api_logout_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
        };
    };
    apps_accounts_api_reauthenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_totp_setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetupOut"];
                };
            };
        };
    };
    apps_accounts_api_totp_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
        };
    };
    apps_accounts_api_webauthn_register_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_webauthn_register_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
        };
    };
    apps_accounts_api_regenerate_recovery_codes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodesOut"];
                };
            };
        };
    };
    apps_accounts_api_list_devices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
        };
    };
    apps_accounts_api_delete_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_list_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
        };
    };
    apps_accounts_api_revoke_other_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokedOut"];
                };
            };
        };
    };
    apps_accounts_api_revoke_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_sign_in_activity: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInOut"][];
                };
            };
        };
    };
    apps_documents_api_list_documents: {
        parameters: {
            query?: {
                q?: string;
                folder?: number[];
                subfolders?: boolean;
                unfiled?: boolean;
                document_type?: number[];
                correspondent?: number[];
                tag?: number[];
                series?: number | null;
                status?: ("new" | "todo" | "done")[];
                important?: boolean | null;
                unread?: boolean | null;
                processing?: ("pending" | "running" | "done" | "failed")[];
                uploaded_from?: string | null;
                uploaded_to?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                sort?: "relevance" | "uploaded" | "-uploaded" | "date" | "-date";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
        };
    };
    apps_documents_api_web_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                    /** Folder Id */
                    folder_id?: number | null;
                    /**
                     * Document Type
                     * @default auto
                     */
                    document_type?: string;
                    /**
                     * Todo
                     * @default false
                     */
                    todo?: boolean;
                    /**
                     * Important
                     * @default false
                     */
                    important?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebUploadOut"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebUploadOut"];
                };
            };
        };
    };
    apps_documents_api_bulk_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkAction"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkOut"];
                };
            };
        };
    };
    apps_documents_api_document_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
        };
    };
    apps_documents_api_delete_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_documents_api_update_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
        };
    };
    apps_documents_api_mark_unread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_documents_api_document_file: {
        parameters: {
            query?: {
                variant?: "archive" | "original";
                download?: boolean;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_documents_api_document_thumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_documents_api_document_text: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextOut"];
                };
            };
        };
    };
    apps_documents_api_document_structure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureOut"];
                };
            };
        };
    };
    apps_documents_api_reprocess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReprocessIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
        };
    };
    apps_taxonomy_api_list_folders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderOut"][];
                };
            };
        };
    };
    apps_taxonomy_api_create_folder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderOut"];
                };
            };
        };
    };
    apps_taxonomy_api_delete_folder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_taxonomy_api_update_folder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderOut"];
                };
            };
        };
    };
    apps_taxonomy_api_list_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeOut"][];
                };
            };
        };
    };
    apps_taxonomy_api_create_type: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeOut"];
                };
            };
        };
    };
    apps_taxonomy_api_delete_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_taxonomy_api_update_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeOut"];
                };
            };
        };
    };
    apps_taxonomy_api_list_tags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    apps_taxonomy_api_create_tag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
        };
    };
    apps_taxonomy_api_delete_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_taxonomy_api_update_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
        };
    };
    apps_taxonomy_api_merge_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
        };
    };
    apps_taxonomy_api_list_correspondents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrespondentOut"][];
                };
            };
        };
    };
    apps_taxonomy_api_create_correspondent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrespondentOut"];
                };
            };
        };
    };
    apps_taxonomy_api_delete_correspondent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corr_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_taxonomy_api_update_correspondent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corr_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrespondentPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrespondentOut"];
                };
            };
        };
    };
    apps_taxonomy_api_merge_correspondent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corr_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrespondentOut"];
                };
            };
        };
    };
    apps_taxonomy_api_list_series: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesOut"][];
                };
            };
        };
    };
    apps_taxonomy_api_create_series: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesOut"];
                };
            };
        };
    };
    apps_taxonomy_api_series_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
        };
    };
    apps_taxonomy_api_delete_series: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_taxonomy_api_update_series: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesOut"];
                };
            };
        };
    };
    apps_taxonomy_api_list_rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    apps_taxonomy_api_create_rule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
        };
    };
    apps_taxonomy_api_delete_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_scanners_api_list_scanners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerOut"][];
                };
            };
        };
    };
    apps_scanners_api_create_scanner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScannerIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerCreated"];
                };
            };
        };
    };
    apps_scanners_api_rotate_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerCreated"];
                };
            };
        };
    };
    apps_scanners_api_revoke_scanner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerOut"];
                };
            };
        };
    };
    apps_scanners_api_delete_scanner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
