# Generated by Django 5.2.17 on 2026-10-04 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("scanner", "Scanner"),
                            ("system", "System"),
                            ("anonymous", "Anonymous"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=64)),
                ("actor_label", models.CharField(blank=True, max_length=150)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("target", models.CharField(blank=True, max_length=200)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
