[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
user=docnest

[program:web]
command=gunicorn docnest.wsgi:application -c /app/backend/docnest/gunicorn.py
directory=/app/backend
autorestart=true
stopsignal=TERM
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker]
command=python manage.py worker
directory=/app/backend
autorestart=true
stopsignal=TERM
stopwaitsecs=120
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
