# Generated by Django 5.2.17 on 2026-10-06

from django.db import migrations, models


def backfill_finished_at(apps, schema_editor):
    job = apps.get_model("processing", "Job")
    job.objects.filter(state__in=["done", "failed"]).update(finished_at=models.F("updated_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_finished_at, migrations.RunPython.noop),
    ]
