# Generated by Django 5.2.17 on 2026-10-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0004_blank_threshold_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="kind",
            field=models.CharField(
                choices=[
                    ("process_document", "Process Document"),
                    ("analyze_document", "Analyze Document"),
                    ("pull_model", "Pull Model"),
                    ("delete_storage", "Delete Storage"),
                    ("train_classifier", "Train Classifier"),
                    ("reindex_document", "Reindex Document"),
                    ("backup_database", "Backup Database"),
                ],
                max_length=40,
            ),
        ),
    ]
