# Generated by Django 5.2.17 on 2026-10-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0005_job_kinds_analyze_pull"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="priority",
            field=models.SmallIntegerField(default=0),
        ),
    ]
