# Generated by Django 5.2.17 on 2026-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0007_intake_and_processing_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="kind",
            field=models.CharField(
                choices=[
                    ("intake_document", "Intake Document"),
                    ("process_document", "Process Document"),
                    ("pull_model", "Pull Model"),
                    ("delete_storage", "Delete Storage"),
                    ("train_classifier", "Train Classifier"),
                    ("reindex_document", "Reindex Document"),
                    ("backup_database", "Backup Database"),
                    ("suggest_filing", "Suggest Filing"),
                    ("fetch_mail", "Fetch Mail"),
                ],
                max_length=40,
            ),
        ),
    ]
