# Generated by Django 5.2.17 on 2026-10-10 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assist", "0001_initial"),
        ("documents", "0011_alteration_documentpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentNote",
            fields=[
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="assist_note",
                        serialize=False,
                        to="documents.document",
                    ),
                ),
                ("note_enc", models.BinaryField()),
                ("text_length", models.PositiveIntegerField(default=0)),
                ("model", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="assisttask",
            name="decisions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="assisttask",
            name="journal_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="assisttask",
            name="model",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="assisttask",
            name="options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="assisttask",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assisttask",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assisttask",
            name="state_enc",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="assisttask",
            name="step",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="assisttask",
            name="operation",
            field=models.CharField(
                choices=[("rename", "Rename"), ("custom", "Custom"), ("review", "Review")], max_length=10
            ),
        ),
    ]
