# Generated by Django 5.2.17 on 2026-10-07 22:54

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_assemble_stage"),
        ("scanners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("completed", "Completed")], default="open", max_length=20
                    ),
                ),
                ("request_enc", models.BinaryField()),
                ("idempotency_hash", models.CharField(blank=True, max_length=64)),
                ("duplicate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.document",
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_sessions",
                        to="scanners.scannerclient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScanPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=10)),
                ("size", models.BigIntegerField()),
                ("digest", models.CharField(max_length=64)),
                ("file_name", models.CharField(max_length=40)),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="scanners.scansession",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddConstraint(
            model_name="scansession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_hash", ""), _negated=True),
                fields=("scanner", "idempotency_hash"),
                name="scan_session_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="scanpage",
            constraint=models.UniqueConstraint(fields=("session", "position"), name="scan_page_unique"),
        ),
    ]
