# Generated by Django 5.2.17 on 2026-10-10 12:52

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0009_processing_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("message_key", models.CharField(max_length=64, unique=True)),
                ("subject_enc", models.BinaryField(null=True)),
                ("sender_enc", models.BinaryField(null=True)),
                ("text_enc", models.BinaryField(null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
    ]
