# Generated by Django 5.2.17 on 2026-10-04 18:06

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("period_label", models.CharField(blank=True, max_length=40)),
                ("title_enc", models.BinaryField(null=True)),
                ("extracted_enc", models.BinaryField(null=True)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("todo", "Todo"), ("done", "Done")],
                        db_index=True,
                        default="new",
                        max_length=10,
                    ),
                ),
                ("is_important", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("original_filename_enc", models.BinaryField(null=True)),
                ("size", models.BigIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=0)),
                (
                    "processing_stage",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("validate", "Validate"),
                            ("ocr", "Ocr"),
                            ("analyze", "Analyze"),
                            ("store", "Store"),
                            ("index", "Index"),
                            ("done", "Done"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "processing_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.CharField(blank=True, max_length=500)),
                ("intake_path", models.CharField(blank=True, max_length=300)),
                ("storage_original", models.JSONField(blank=True, null=True)),
                ("storage_archive", models.JSONField(blank=True, null=True)),
                ("field_sources", models.JSONField(blank=True, default=dict)),
                ("scanner_metadata_enc", models.BinaryField(null=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="taxonomy.bucket",
                    ),
                ),
                (
                    "correspondent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxonomy.correspondent",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxonomy.documenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "Auto"), ("scanner", "Scanner"), ("user", "User")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stage", models.CharField(max_length=20)),
                ("outcome", models.CharField(max_length=20)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentContent",
            fields=[
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="content",
                        serialize=False,
                        to="documents.document",
                    ),
                ),
                ("text_enc", models.BinaryField()),
                ("language", models.CharField(blank=True, max_length=10)),
                ("length", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentThumbnail",
            fields=[
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="thumbnail",
                        serialize=False,
                        to="documents.document",
                    ),
                ),
                ("image_enc", models.BinaryField()),
            ],
        ),
    ]
