# Generated by Django 5.2.17 on 2026-10-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("scanners", "0001_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="received_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="scanners.scannerclient",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="taxonomy.series",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="series_suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggested_documents",
                to="taxonomy.series",
            ),
        ),
        migrations.AddField(
            model_name="documenttag",
            name="document",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="documents.document"),
        ),
        migrations.AddField(
            model_name="documenttag",
            name="tag",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxonomy.tag"),
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(
                related_name="documents", through="documents.DocumentTag", to="taxonomy.tag"
            ),
        ),
        migrations.AddField(
            model_name="processingevent",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="events", to="documents.document"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttag",
            constraint=models.UniqueConstraint(fields=("document", "tag"), name="document_tag_unique"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["document_date"], name="documents_d_documen_0eb394_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status", "uploaded_at"], name="documents_d_status_7e2894_idx"),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("content_hash",),
                name="document_hash_unique_active",
            ),
        ),
    ]
