# Generated by Django 5.2.17 on 2026-10-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_documentcontent_layout_enc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="processing_stage",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("assemble", "Assemble"),
                    ("validate", "Validate"),
                    ("ocr", "Ocr"),
                    ("analyze", "Analyze"),
                    ("store", "Store"),
                    ("index", "Index"),
                    ("done", "Done"),
                ],
                default="received",
                max_length=20,
            ),
        ),
    ]
