# Generated by Django 5.2.17 on 2026-10-08 01:05

from django.db import migrations, models
from django.db.models import F


def copy_page_count(apps, schema_editor):
    # Existing documents were never enhanced: their original has the shown page count.
    Document = apps.get_model("documents", "Document")
    Document.objects.update(original_page_count=F("page_count"))


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_buckets_to_folders"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="enhancement",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="document",
            name="original_page_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="document",
            name="processing_stage",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("assemble", "Assemble"),
                    ("validate", "Validate"),
                    ("enhance", "Enhance"),
                    ("ocr", "Ocr"),
                    ("analyze", "Analyze"),
                    ("store", "Store"),
                    ("index", "Index"),
                    ("done", "Done"),
                ],
                default="received",
                max_length=20,
            ),
        ),
        migrations.RunPython(copy_page_count, migrations.RunPython.noop),
    ]
