# Generated by Django 5.2.17 on 2026-10-08 01:20

import django.db.models.deletion
from django.db import migrations, models


def scanned_documents_have_paper(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    Document.objects.filter(received_from__isnull=False).update(has_paper=True)


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_enhance_stage"),
        ("paper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="has_paper",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="paper_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="paper.location",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="paper_placed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(scanned_documents_have_paper, migrations.RunPython.noop),
    ]
