# Generated by Django 5.2.17 on 2026-10-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_paper_original"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="processing_plan",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
