# Generated by Django 5.2.17 on 2026-10-10 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_processing_plan"),
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="mail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="mail.mailmessage",
            ),
        ),
    ]
