# Generated by Django 5.2.17 on 2026-10-10 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_document_mail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alteration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("compose", "Compose"),
                            ("trash", "Trash"),
                            ("restore", "Restore"),
                            ("edit", "Edit"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")], default="user", max_length=10
                    ),
                ),
                ("sources", models.JSONField(default=list)),
                ("results", models.JSONField(default=list)),
                ("retired", models.JSONField(default=list)),
                ("detail_enc", models.BinaryField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("thumbnail_enc", models.BinaryField(null=True)),
                ("fingerprint_enc", models.BinaryField(null=True)),
                ("version", models.CharField(max_length=64)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_prints",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "number"],
                "constraints": [
                    models.UniqueConstraint(fields=("document", "number"), name="document_page_unique")
                ],
            },
        ),
    ]
