# Generated by Django 5.2.17 on 2026-10-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentStats",
            fields=[
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="documents.document",
                    ),
                ),
                ("length", models.PositiveIntegerField(default=0)),
                ("signature", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("term", models.BigIntegerField()),
                ("field", models.SmallIntegerField(choices=[(1, "Title"), (2, "Content"), (3, "Meta")])),
                ("tf", models.SmallIntegerField(default=1)),
                (
                    "document",
                    models.ForeignKey(
                        db_index=False, on_delete=django.db.models.deletion.CASCADE, to="documents.document"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["term"], name="search_term_idx"),
                    models.Index(fields=["document"], name="search_term_doc_idx"),
                ],
            },
        ),
    ]
