# Generated by Django 5.2.17 on 2026-10-04 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassifierModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target", models.CharField(max_length=40, unique=True)),
                ("model", models.JSONField(default=dict)),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("trained_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
