# Generated by Django 5.2.17 on 2026-10-10 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0004_delete_bucket"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilingProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("pending", "Pending"), ("done", "Done"), ("failed", "Failed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("documents", models.JSONField(default=list)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
