# Generated by Django 5.2.17 on 2026-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0005_filingproposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="filingproposal",
            name="options",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
